In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("../dados/shop-sales-data.csv")

In [6]:
df.head()

   year  month shop_id   product_id  sales_qty
0     2      2  shop_0  product_268       2.00
1     2      4  shop_0  product_268       2.00
2     2      9  shop_0  product_268       2.00
3     2      3  shop_0  product_269       0.95
4     2      7  shop_0  product_269       0.95

In [16]:
df["year"].value_counts().sort_index()

year
0      56175
1    1949491
2    4242144
3    4447213
4     763330
Name: count, dtype: int64

In [17]:
df.sort_values(["year", "month"]).head(20)

      year  month   shop_id    product_id  sales_qty
1640     0      1  shop_100  product_1005       0.89
1647     0      1  shop_100  product_1006       1.01
1656     0      1  shop_100  product_1007       0.98
1665     0      1  shop_100  product_1008       0.98
1677     0      1  shop_100  product_1017      45.02
1708     0      1  shop_100  product_1034       7.27
1716     0      1  shop_100  product_1035      31.46
1723     0      1  shop_100  product_1037      29.83
1732     0      1  shop_100  product_1039      13.36
1736     0      1  shop_100  product_1040       1.84
1752     0      1  shop_100  product_1041       1.99
1765     0      1  shop_100  product_1042      25.55
1799     0      1  shop_100  product_1061     115.84
1957     0      1  shop_100  product_1105       0.93
2020     0      1  shop_100   product_115      15.66
2144     0      1  shop_100  product_1185      23.96
2284     0      1  shop_100  product_1210       6.30
2296     0      1  shop_100  product_1213       7.52
2313     0      1  shop_100  product_1215      20.61
2333     0      1  shop_100  product_1219      37.24

In [7]:
df.shape

(11458353, 5)

In [8]:
df.columns

Index(['year', 'month', 'shop_id', 'product_id', 'sales_qty'], dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11458353 entries, 0 to 11458352
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   year        int64
 1   month       int64
 2   shop_id     str
 3   product_id  str
 4   sales_qty   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 437.1 MB

In [11]:
df.isnull().sum()

year          0
month         0
shop_id       0
product_id    0
sales_qty     0
dtype: int64

In [12]:
df["year"].unique()

array([2, 3, 0, 1, 4])

In [13]:
sorted(df["month"].unique())

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12)]

In [14]:
df["shop_id"].nunique()

105252

In [15]:
df["product_id"].nunique()

1353